baseURL = "https://iacmac-web-tools.github.io"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "Евразийский конгресс по антимикробной терапии и клинической микробиологии"
publishDir = "docs"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = ""

[params]
    title = "Евразийский конгресс по антимикробной терапии и клинической микробиологии"
    date = "2019-10-17"
    description = "Евразийский конгресс по антимикробной терапии и клинической микробиологии состоится 17–18 октября 2019 г. в Уфе. Место проведения: Республика Башкортостан, г. Уфа, ул. Заки Валиди, 2; ГБУ РБ «Конгресс-холл Торатау»."
    images = ["/images/social-share.jpg"]
    email = "conference@antibiotic.ru"
    keywords = ""
    copyright = "МАКМАХ"
    cfpUrl = ""
    subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

#[menu]
#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = true

[languages]
[languages.ru]
    weight = 1
    languageName = "ru"

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
